import { GoogleOAuthProvider } from '@react-oauth/google'
import { GeistSans, GeistMono } from 'geist/font'
import './globals.css'

export const metadata = {
  title: 'Formula Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <GoogleOAuthProvider clientId="98233543291-c69vq4mhmjtdtgac6mclbsee22jsqmlt.apps.googleusercontent.com">
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  )
}
